// Zenithia — Monster Data

const MONSTERS = {
  moss_beetle: {
    name: 'Moss Beetle',
    level: 1,
    hp: 30,
    atk: 5,
    def: 8,
    spd: 2,
    xp: 15,
    zen: [5, 15],
    color: 0x4CAF50,
    accentColor: 0x81C784,
    size: 0.6,
    aggroRange: 5,
    attackRange: 1.5,
    attackSpeed: 1.5,
    behavior: 'passive', // only attacks if hit first
    retreatHp: 0.2,
    spawnAreas: [
      { x: -10, z: -20, radius: 15 },
      { x: 5, z: -18, radius: 10 },
    ],
    maxSpawn: 6,
    respawnTime: 30,
  },

  dust_mouse: {
    name: 'Dust Mouse',
    level: 1,
    hp: 15,
    atk: 3,
    def: 2,
    spd: 6,
    xp: 10,
    zen: [3, 10],
    color: 0xBCAAA4,
    accentColor: 0xD7CCC8,
    size: 0.35,
    aggroRange: 3,
    attackRange: 1,
    attackSpeed: 0.8,
    behavior: 'skittish', // runs away, explodes if cornered
    retreatHp: 0.5,
    spawnAreas: [
      { x: -18, z: 15, radius: 8 },
      { x: -15, z: 8, radius: 6 },
    ],
    maxSpawn: 8,
    respawnTime: 20,
  },

  thorn_lizard: {
    name: 'Thorn Lizard',
    level: 2,
    hp: 45,
    atk: 8,
    def: 5,
    spd: 4,
    xp: 25,
    zen: [8, 20],
    color: 0x689F38,
    accentColor: 0x8BC34A,
    size: 0.7,
    aggroRange: 6,
    attackRange: 1.5,
    attackSpeed: 1.2,
    behavior: 'pack', // attacks in groups of 2-3
    retreatHp: 0.15,
    spawnAreas: [
      { x: -8, z: -25, radius: 12 },
      { x: 3, z: -22, radius: 10 },
    ],
    maxSpawn: 5,
    respawnTime: 40,
  },

  puddle_frog: {
    name: 'Puddle Frog',
    level: 2,
    hp: 35,
    atk: 6,
    def: 3,
    spd: 5,
    xp: 20,
    zen: [7, 18],
    color: 0x00BCD4,
    accentColor: 0x4DD0E1,
    size: 0.55,
    aggroRange: 4,
    attackRange: 2,
    attackSpeed: 1.0,
    behavior: 'ambush', // hides in water, jumps out
    retreatHp: 0.3,
    spawnAreas: [
      { x: -10, z: 2, radius: 5 },
      { x: 0, z: 2, radius: 8 },
    ],
    maxSpawn: 4,
    respawnTime: 35,
  },

  wind_sprite: {
    name: 'Wind Sprite',
    level: 3,
    hp: 25,
    atk: 10,
    def: 1,
    spd: 8,
    xp: 35,
    zen: [10, 25],
    color: 0x81D4FA,
    accentColor: 0xB3E5FC,
    size: 0.4,
    aggroRange: 7,
    attackRange: 3,
    attackSpeed: 0.6,
    behavior: 'trickster', // steals items, immune to melee
    retreatHp: 0.4,
    spawnAreas: [
      { x: 10, z: -15, radius: 10 },
      { x: -5, z: -30, radius: 8 },
    ],
    maxSpawn: 3,
    respawnTime: 60,
    immuneToMelee: true,
  },

  rock_crawler: {
    name: 'Rock Crawler',
    level: 3,
    hp: 55,
    atk: 7,
    def: 12,
    spd: 1,
    xp: 30,
    zen: [12, 28],
    color: 0x9E9E9E,
    accentColor: 0xBDBDBD,
    size: 0.45,
    aggroRange: 2,
    attackRange: 1.5,
    attackSpeed: 2.0,
    behavior: 'camouflaged', // looks like rock until approached
    retreatHp: 0.1,
    spawnAreas: [
      { x: -15, z: -8, radius: 5 },
      { x: 14, z: 10, radius: 5 },
    ],
    maxSpawn: 4,
    respawnTime: 45,
  },

  bramble_boar: {
    name: 'Bramble Boar',
    level: 5,
    hp: 120,
    atk: 15,
    def: 10,
    spd: 7,
    xp: 80,
    zen: [25, 50],
    color: 0x5D4037,
    accentColor: 0x8D6E63,
    size: 1.2,
    aggroRange: 8,
    attackRange: 2,
    attackSpeed: 1.8,
    behavior: 'aggressive', // charges at player
    retreatHp: 0.05,
    spawnAreas: [
      { x: -5, z: -35, radius: 10 },
    ],
    maxSpawn: 2,
    respawnTime: 120,
    chargeDamage: 25,
  },
};

module.exports = MONSTERS;
