// Zenithia — Monster Data

const MONSTERS = {
  moss_beetle: {
    name: 'Moss Beetle',
    level: 1,
    hp: 30,
    atk: 5,
    def: 8,
    spd: 2,
    xp: 15,
    zen: [0, 0],
    color: 0x4CAF50,
    accentColor: 0x81C784,
    size: 0.6,
    aggroRange: 8,
    attackRange: 1.5,
    attackSpeed: 1.5,
    behavior: 'passive', // only attacks if hit first
    retreatHp: 0.2,
    spawnAreas: [
      { x: -10, z: -20, radius: 15 },
      { x: 5, z: -18, radius: 10 },
    ],
    maxSpawn: 6,
    respawnTime: 30,
  },

  dust_mouse: {
    name: 'Dust Mouse',
    level: 1,
    hp: 15,
    atk: 3,
    def: 2,
    spd: 6,
    xp: 10,
    zen: [0, 0],
    color: 0xBCAAA4,
    accentColor: 0xD7CCC8,
    size: 0.35,
    aggroRange: 5,
    attackRange: 1,
    attackSpeed: 0.8,
    behavior: 'skittish', // runs away, explodes if cornered
    retreatHp: 0.5,
    spawnAreas: [
      { x: -18, z: 15, radius: 8 },
      { x: -15, z: 8, radius: 6 },
    ],
    maxSpawn: 8,
    respawnTime: 20,
  },

  thorn_lizard: {
    name: 'Thorn Lizard',
    level: 2,
    hp: 45,
    atk: 8,
    def: 5,
    spd: 4,
    xp: 25,
    zen: [0, 0],
    color: 0x689F38,
    accentColor: 0x8BC34A,
    size: 0.7,
    aggroRange: 10,
    attackRange: 1.5,
    attackSpeed: 1.2,
    behavior: 'pack', // attacks in groups of 2-3
    retreatHp: 0.15,
    spawnAreas: [
      { x: -8, z: -25, radius: 12 },
      { x: 3, z: -22, radius: 10 },
    ],
    maxSpawn: 5,
    respawnTime: 40,
  },

  puddle_frog: {
    name: 'Puddle Frog',
    level: 2,
    hp: 35,
    atk: 6,
    def: 3,
    spd: 5,
    xp: 20,
    zen: [0, 0],
    color: 0x00BCD4,
    accentColor: 0x4DD0E1,
    size: 0.55,
    aggroRange: 7,
    attackRange: 2,
    attackSpeed: 1.0,
    behavior: 'ambush', // hides in water, jumps out
    retreatHp: 0.3,
    spawnAreas: [
      { x: -10, z: 2, radius: 5 },
      { x: 0, z: 2, radius: 8 },
    ],
    maxSpawn: 4,
    respawnTime: 35,
  },

  wind_sprite: {
    name: 'Wind Sprite',
    level: 3,
    hp: 25,
    atk: 10,
    def: 1,
    spd: 8,
    xp: 35,
    zen: [0, 0],
    color: 0x81D4FA,
    accentColor: 0xB3E5FC,
    size: 0.4,
    aggroRange: 11,
    attackRange: 3,
    attackSpeed: 0.6,
    behavior: 'trickster', // steals items, immune to melee
    retreatHp: 0.4,
    spawnAreas: [
      { x: 10, z: -15, radius: 10 },
      { x: -5, z: -30, radius: 8 },
    ],
    maxSpawn: 3,
    respawnTime: 60,
    immuneToMelee: true,
  },

  rock_crawler: {
    name: 'Rock Crawler',
    level: 3,
    hp: 55,
    atk: 7,
    def: 12,
    spd: 1,
    xp: 30,
    zen: [0, 0],
    color: 0x9E9E9E,
    accentColor: 0xBDBDBD,
    size: 0.45,
    aggroRange: 4,
    attackRange: 1.5,
    attackSpeed: 2.0,
    behavior: 'camouflaged', // looks like rock until approached
    retreatHp: 0.1,
    spawnAreas: [
      { x: -15, z: -8, radius: 5 },
      { x: 14, z: 10, radius: 5 },
    ],
    maxSpawn: 4,
    respawnTime: 45,
  },

  marsh_snapper: {
    name: 'Marsh Snapper',
    level: 8,
    hp: 180,
    atk: 18,
    def: 15,
    spd: 3,
    xp: 120,
    zen: [0, 0],
    color: 0x2E7D32,
    accentColor: 0x66BB6A,
    size: 1.0,
    aggroRange: 12,
    attackRange: 2,
    attackSpeed: 1.5,
    behavior: 'aggressive',
    retreatHp: 0.1,
    spawnAreas: [
      { x: -15, z: -15, radius: 12 },
      { x: 15, z: 10, radius: 10 },
    ],
    maxSpawn: 4,
    respawnTime: 90,
  },

  bramble_boar: {
    name: 'Bramble Boar',
    level: 5,
    hp: 120,
    atk: 15,
    def: 10,
    spd: 7,
    xp: 80,
    zen: [0, 0],
    color: 0x5D4037,
    accentColor: 0x8D6E63,
    size: 1.2,
    aggroRange: 13,
    attackRange: 2,
    attackSpeed: 1.8,
    behavior: 'aggressive', // charges at player
    retreatHp: 0.05,
    spawnAreas: [
      { x: -5, z: -35, radius: 10 },
    ],
    maxSpawn: 2,
    respawnTime: 120,
    chargeDamage: 25,
  },

  // ═══════════════════════════════════════
  // STORMCREST MOUNTAINS (Lv.5-8) — unique
  // ═══════════════════════════════════════
  storm_hawk: {
    name: 'Storm Hawk',
    level: 6,
    hp: 80,
    atk: 16,
    def: 4,
    spd: 10,
    xp: 90,
    zen: [0, 0],
    color: 0x78909C,
    accentColor: 0xB0BEC5,
    size: 0.65,
    aggroRange: 14,
    attackRange: 2.5,
    attackSpeed: 0.8,
    behavior: 'diver', // swoops down from above
    retreatHp: 0.3,
    maxSpawn: 3,
    respawnTime: 50,
  },

  stone_golem: {
    name: 'Stone Golem',
    level: 7,
    hp: 200,
    atk: 14,
    def: 25,
    spd: 1,
    xp: 110,
    zen: [0, 0],
    color: 0x616161,
    accentColor: 0x9E9E9E,
    size: 1.4,
    aggroRange: 6,
    attackRange: 2,
    attackSpeed: 2.5,
    behavior: 'guardian', // slow but hits hard, high def
    retreatHp: 0.05,
    maxSpawn: 2,
    respawnTime: 90,
  },

  // ═══════════════════════════════════════
  // MISTMARSH SWAMP (Lv.8-10) — unique
  // ═══════════════════════════════════════
  swamp_lurker: {
    name: 'Swamp Lurker',
    level: 9,
    hp: 150,
    atk: 22,
    def: 10,
    spd: 6,
    xp: 140,
    zen: [0, 0],
    color: 0x1B5E20,
    accentColor: 0x4CAF50,
    size: 0.9,
    aggroRange: 10,
    attackRange: 2,
    attackSpeed: 1.2,
    behavior: 'ambush', // hides in swamp, attacks from behind
    retreatHp: 0.15,
    maxSpawn: 3,
    respawnTime: 60,
  },

  toxic_toad: {
    name: 'Toxic Toad',
    level: 8,
    hp: 100,
    atk: 12,
    def: 6,
    spd: 4,
    xp: 100,
    zen: [0, 0],
    color: 0x7B1FA2,
    accentColor: 0xCE93D8,
    size: 0.7,
    aggroRange: 8,
    attackRange: 3,
    attackSpeed: 1.0,
    behavior: 'poisoner', // shoots poison projectiles, DoT
    retreatHp: 0.2,
    maxSpawn: 4,
    respawnTime: 45,
  },
  // ═══════════════════════════════════════
  // VOLCANIC WASTES (Lv.10-20)
  // ═══════════════════════════════════════
  lava_slime: {
    name: 'Lava Slime',
    level: 10,
    hp: 80,
    atk: 12,
    def: 6,
    spd: 3,
    xp: 80,
    zen: [0, 0],
    color: 0xFF6D00,
    accentColor: 0xFF9100,
    size: 0.7,
    aggroRange: 8,
    attackRange: 1.5,
    attackSpeed: 1.0,
    behavior: 'aggressive',
    retreatHp: 0.2,
    spawnAreas: [
      { x: 60, z: 40, radius: 18 },
      { x: 75, z: 55, radius: 15 },
      { x: 55, z: 65, radius: 12 },
    ],
    maxSpawn: 6,
    respawnTime: 45,
  },

  fire_salamander: {
    name: 'Fire Salamander',
    level: 12,
    hp: 100,
    atk: 15,
    def: 8,
    spd: 6,
    xp: 110,
    zen: [0, 0],
    color: 0xDD2C00,
    accentColor: 0xFF6E40,
    size: 0.9,
    aggroRange: 10,
    attackRange: 2,
    attackSpeed: 1.2,
    behavior: 'pack',
    retreatHp: 0.15,
    spawnAreas: [
      { x: 80, z: 35, radius: 20 },
      { x: 65, z: 50, radius: 16 },
    ],
    maxSpawn: 4,
    respawnTime: 60,
  },

  magma_golem: {
    name: 'Magma Golem',
    level: 15,
    hp: 200,
    atk: 20,
    def: 18,
    spd: 1,
    xp: 180,
    zen: [0, 0],
    color: 0xBF360C,
    accentColor: 0xE65100,
    size: 1.5,
    aggroRange: 6,
    attackRange: 2.5,
    attackSpeed: 2.5,
    behavior: 'guardian',
    retreatHp: 0.05,
    spawnAreas: [
      { x: 90, z: 60, radius: 12 },
      { x: 70, z: 70, radius: 10 },
      { x: 95, z: 45, radius: 8 },
    ],
    maxSpawn: 2,
    respawnTime: 120,
  },

  ember_hawk: {
    name: 'Ember Hawk',
    level: 18,
    hp: 90,
    atk: 22,
    def: 5,
    spd: 10,
    xp: 200,
    zen: [0, 0],
    color: 0xFF3D00,
    accentColor: 0xFFAB40,
    size: 0.6,
    aggroRange: 15,
    attackRange: 3,
    attackSpeed: 0.8,
    behavior: 'diver',
    retreatHp: 0.3,
    spawnAreas: [
      { x: 85, z: 40, radius: 20 },
      { x: 60, z: 60, radius: 15 },
    ],
    maxSpawn: 3,
    respawnTime: 50,
  },

  // ═══════════════════════════════════════
  // CRYSTAL CAVERNS (Lv.20-30)
  // ═══════════════════════════════════════
  crystal_spider: {
    name: 'Crystal Spider',
    level: 20,
    hp: 150,
    atk: 25,
    def: 10,
    spd: 7,
    xp: 250,
    zen: [0, 0],
    color: 0xAA00FF,
    accentColor: 0xEA80FC,
    size: 0.8,
    aggroRange: 10,
    attackRange: 2,
    attackSpeed: 1.0,
    behavior: 'ambush',
    retreatHp: 0.2,
    spawnAreas: [
      { x: 120, z: 80, radius: 20 },
      { x: 105, z: 95, radius: 18 },
      { x: 135, z: 70, radius: 14 },
    ],
    maxSpawn: 5,
    respawnTime: 50,
  },

  gem_scorpion: {
    name: 'Gem Scorpion',
    level: 22,
    hp: 180,
    atk: 28,
    def: 14,
    spd: 5,
    xp: 300,
    zen: [0, 0],
    color: 0xD500F9,
    accentColor: 0xF48FB1,
    size: 1.0,
    aggroRange: 12,
    attackRange: 2.5,
    attackSpeed: 1.2,
    behavior: 'aggressive',
    retreatHp: 0.15,
    spawnAreas: [
      { x: 130, z: 90, radius: 16 },
      { x: 110, z: 100, radius: 20 },
    ],
    maxSpawn: 4,
    respawnTime: 60,
  },

  prism_wraith: {
    name: 'Prism Wraith',
    level: 25,
    hp: 250,
    atk: 30,
    def: 12,
    spd: 4,
    xp: 400,
    zen: [0, 0],
    color: 0xE040FB,
    accentColor: 0xFF80AB,
    size: 1.1,
    aggroRange: 14,
    attackRange: 3,
    attackSpeed: 1.5,
    behavior: 'trickster',
    retreatHp: 0.25,
    spawnAreas: [
      { x: 140, z: 75, radius: 15 },
      { x: 125, z: 85, radius: 12 },
      { x: 150, z: 95, radius: 10 },
    ],
    maxSpawn: 3,
    respawnTime: 75,
  },

  diamond_golem: {
    name: 'Diamond Golem',
    level: 28,
    hp: 350,
    atk: 28,
    def: 30,
    spd: 1,
    xp: 500,
    zen: [0, 0],
    color: 0x7B1FA2,
    accentColor: 0xCE93D8,
    size: 1.6,
    aggroRange: 6,
    attackRange: 2.5,
    attackSpeed: 3.0,
    behavior: 'guardian',
    retreatHp: 0.05,
    spawnAreas: [
      { x: 145, z: 80, radius: 10 },
      { x: 120, z: 70, radius: 8 },
    ],
    maxSpawn: 2,
    respawnTime: 150,
  },

  // ═══════════════════════════════════════
  // SKY RUINS (Lv.30-40)
  // ═══════════════════════════════════════
  storm_elemental: {
    name: 'Storm Elemental',
    level: 30,
    hp: 300,
    atk: 35,
    def: 15,
    spd: 5,
    xp: 600,
    zen: [0, 0],
    color: 0x2979FF,
    accentColor: 0x82B1FF,
    size: 1.2,
    aggroRange: 12,
    attackRange: 4,
    attackSpeed: 1.2,
    behavior: 'aggressive',
    retreatHp: 0.2,
    spawnAreas: [
      { x: 180, z: 120, radius: 22 },
      { x: 165, z: 135, radius: 18 },
      { x: 195, z: 110, radius: 15 },
    ],
    maxSpawn: 4,
    respawnTime: 75,
  },

  cloud_serpent: {
    name: 'Cloud Serpent',
    level: 33,
    hp: 280,
    atk: 38,
    def: 10,
    spd: 9,
    xp: 700,
    zen: [0, 0],
    color: 0x448AFF,
    accentColor: 0xB3E5FC,
    size: 0.9,
    aggroRange: 14,
    attackRange: 3.5,
    attackSpeed: 0.9,
    behavior: 'pack',
    retreatHp: 0.25,
    spawnAreas: [
      { x: 190, z: 130, radius: 20 },
      { x: 175, z: 140, radius: 16 },
    ],
    maxSpawn: 3,
    respawnTime: 60,
  },

  sky_knight: {
    name: 'Sky Knight',
    level: 36,
    hp: 400,
    atk: 40,
    def: 22,
    spd: 4,
    xp: 850,
    zen: [0, 0],
    color: 0x1565C0,
    accentColor: 0xE3F2FD,
    size: 1.4,
    aggroRange: 16,
    attackRange: 2.5,
    attackSpeed: 1.5,
    behavior: 'aggressive',
    retreatHp: 0.1,
    spawnAreas: [
      { x: 200, z: 125, radius: 12 },
      { x: 185, z: 145, radius: 10 },
      { x: 170, z: 115, radius: 8 },
    ],
    maxSpawn: 2,
    respawnTime: 120,
  },

  thunder_bird: {
    name: 'Thunder Bird',
    level: 39,
    hp: 350,
    atk: 42,
    def: 12,
    spd: 11,
    xp: 1000,
    zen: [0, 0],
    color: 0x0D47A1,
    accentColor: 0xFFFFFF,
    size: 1.0,
    aggroRange: 18,
    attackRange: 3,
    attackSpeed: 0.7,
    behavior: 'diver',
    retreatHp: 0.3,
    spawnAreas: [
      { x: 210, z: 130, radius: 18 },
      { x: 195, z: 150, radius: 14 },
    ],
    maxSpawn: 2,
    respawnTime: 90,
  },

  // ═══════════════════════════════════════
  // ABYSS (Lv.40-50)
  // ═══════════════════════════════════════
  void_stalker: {
    name: 'Void Stalker',
    level: 42,
    hp: 500,
    atk: 45,
    def: 18,
    spd: 8,
    xp: 1200,
    zen: [0, 0],
    color: 0x4A148C,
    accentColor: 0x6A1B9A,
    size: 1.1,
    aggroRange: 16,
    attackRange: 2.5,
    attackSpeed: 1.2,
    behavior: 'ambush',
    retreatHp: 0.2,
    spawnAreas: [
      { x: 250, z: 180, radius: 20 },
      { x: 235, z: 195, radius: 18 },
      { x: 265, z: 170, radius: 14 },
    ],
    maxSpawn: 4,
    respawnTime: 90,
  },

  shadow_beast: {
    name: 'Shadow Beast',
    level: 45,
    hp: 600,
    atk: 50,
    def: 20,
    spd: 6,
    xp: 1500,
    zen: [0, 0],
    color: 0x311B92,
    accentColor: 0x1A1A2E,
    size: 1.5,
    aggroRange: 14,
    attackRange: 2.5,
    attackSpeed: 1.5,
    behavior: 'aggressive',
    retreatHp: 0.1,
    spawnAreas: [
      { x: 260, z: 190, radius: 18 },
      { x: 240, z: 200, radius: 15 },
    ],
    maxSpawn: 3,
    respawnTime: 120,
  },

  abyssal_worm: {
    name: 'Abyssal Worm',
    level: 48,
    hp: 800,
    atk: 55,
    def: 15,
    spd: 2,
    xp: 1800,
    zen: [0, 0],
    color: 0x1A0033,
    accentColor: 0x2D004D,
    size: 1.8,
    aggroRange: 8,
    attackRange: 3,
    attackSpeed: 2.5,
    behavior: 'guardian',
    retreatHp: 0.05,
    spawnAreas: [
      { x: 270, z: 185, radius: 15 },
      { x: 255, z: 210, radius: 12 },
      { x: 280, z: 175, radius: 10 },
    ],
    maxSpawn: 2,
    respawnTime: 180,
  },

  chaos_lord: {
    name: 'Chaos Lord',
    level: 50,
    hp: 1000,
    atk: 60,
    def: 25,
    spd: 3,
    xp: 2500,
    zen: [0, 0],
    color: 0x0D0D0D,
    accentColor: 0x6A0DAD,
    size: 2.0,
    aggroRange: 20,
    attackRange: 3.5,
    attackSpeed: 2.0,
    behavior: 'aggressive',
    retreatHp: 0.05,
    spawnAreas: [
      { x: 280, z: 200, radius: 10 },
      { x: 265, z: 180, radius: 8 },
    ],
    maxSpawn: 1,
    respawnTime: 300,
  },
};

module.exports = MONSTERS;
